Update dotfiles scripts.

diff --git a/bin/utils/dotfiles/dotbackup b/bin/utils/dotfiles/dotbackup
--- a/bin/utils/dotfiles/dotbackup
+++ b/bin/utils/dotfiles/dotbackup
@@ -17,6 +17,7 @@
 # Author : Mark Lucernas -- https://github.com/marklcrns
 # Date   : 2020-08-02
 
+
 # Default script variables
 DOTFILES_BACKUP_DIR="${HOME}/.dotfiles.bak"
 DOTFILES_LIST=()
@@ -24,10 +25,29 @@ BACKUP_DIR_NAME="$(date +"%Y-%m-%dT%H:%M:%S")_old_dotfiles.bak"
 LOG_FILE_DIR="${HOME}/log"
 LOG_FILE="$(date +"%Y-%m-%dT%H:%M:%S")_$(basename -- $0).log"
 
+SCRIPTPATH="$( cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 ; pwd -P )"
+
+# Ansi color code variables
+RED="\e[0;91m"
+BLUE="\e[0;94m"
+GREEN="\e[0;92m"
+YELLOW="\033[1;33m"
+WHITE="\e[0;97m"
+EXPAND_BG="\e[K"
+RED_BG="\e[0;101m${expand_bg}"
+BLUE_BG="\e[0;104m${expand_bg}"
+GREEN_BG="\e[0;102m${expand_bg}"
+YELLOW_BG="\e[0;103m${expand_bg}"
+BOLD="\e[1m"
+ULINE="\e[4m"
+NC="\e[0m" # No/reset color
+
+
 # Source rc file if exist
 if [[ -e "${DOTFILESRC}" ]]; then
   source "${DOTFILESRC}"
 fi
+
 
 # Display help
 usage() {
@@ -58,43 +78,11 @@ while getopts "dsvyh" opt; do
     v) [[ -n "$IS_VERBOSE"   ]] && unset IS_VERBOSE   || IS_VERBOSE=true;;
     y) [[ -n "$SKIP_CONFIRM" ]] && unset SKIP_CONFIRM || SKIP_CONFIRM=true;;
     h) usage && exit 0;;
-    *) error "Invalid flag.";;
+    *) usage && echo -e "${SCRIPTPATH}:\n${RED}ERROR: Invalid flag.${NC}"
+      exit 1
   esac
 done 2>/dev/null
 shift "$((OPTIND-1))" # explanation https://unix.stackexchange.com/a/214151
-
-SCRIPTPATH="$( cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 ; pwd -P )"
-
-# Log stdout and stderr to $LOG_FILE in $LOG_FILE_DIR
-if [[ -n "${DEBUG}" ]]; then
-
-  # Strip trailing '/' in LOG_FILE_DIR path and append "/$LOG_FILE"
-  LOG_FILE_PATH="$(echo ${LOG_FILE_DIR} | sed -r "s,(.*)/$,\1,")/${LOG_FILE}"
-
-  # Create log directory if not existing
-  if [[ ! -d "${LOG_FILE_DIR}" ]]; then
-    mkdir -p "${LOG_FILE_DIR}"
-  fi
-
-  # Initialize log file
-  echo -e "${SCRIPT_PATH} log outputs\n" > ${LOG_FILE_PATH}
-fi
-
-# Ansi color code variables
-# Ref: https://techstop.github.io/bash-script-colors/
-RED="\e[0;91m"
-BLUE="\e[0;94m"
-GREEN="\e[0;92m"
-YELLOW="\033[1;33m"
-WHITE="\e[0;97m"
-EXPAND_BG="\e[K"
-RED_BG="\e[0;101m${expand_bg}"
-BLUE_BG="\e[0;104m${expand_bg}"
-GREEN_BG="\e[0;102m${expand_bg}"
-YELLOW_BG="\e[0;103m${expand_bg}"
-BOLD="\e[1m"
-ULINE="\e[4m"
-NC="\e[0m" # No/reset color
 
 # Stores message into $IN if string argument is passed in, else read from stdin
 # and store it in $IN (used with pipe '|').  Only log message on debug mode.
@@ -167,8 +155,26 @@ error() {
   fi
 }
 
+# Strip trailing '/' in DIR path variables
+DOTFILES_DEST_DIR=$(echo ${DOTFILES_DEST_DIR} | sed -r "s,(.*)/$,\1,")
+LOG_FILE_DIR=$(echo ${LOG_FILE_DIR} | sed -r "s,(.*)/$,\1,")
+
+# Log stdout and stderr to $LOG_FILE in $LOG_FILE_DIR
+if [[ -n "${DEBUG}" ]]; then
+  # Strip trailing '/' in LOG_FILE_DIR path and append "/$LOG_FILE"
+  LOG_FILE_PATH="$(echo ${LOG_FILE_DIR} | sed -r "s,(.*)/$,\1,")/${LOG_FILE}"
+  # Create log directory if not existing
+  if [[ ! -d "${LOG_FILE_DIR}" ]]; then
+    mkdir -p "${LOG_FILE_DIR}"
+  fi
+  # Initialize log file
+  echo -e "${SCRIPTPATH} log outputs\n" > ${LOG_FILE_PATH}
+fi
+
+################################# START SCRIPT #################################
 
 dotfiles_count=0
+
 echolog "Backing up the following files in '${DOTFILES_BACKUP_DIR}/${BACKUP_DIR_NAME}'..."
 for dotfile in ${DOTFILES_LIST[@]};
 do
diff --git a/bin/utils/dotfiles/dotdist b/bin/utils/dotfiles/dotdist
--- a/bin/utils/dotfiles/dotdist
+++ b/bin/utils/dotfiles/dotdist
@@ -59,7 +59,8 @@ while getopts "dsvVyh" opt; do
     V) [[ -n "$IS_VERY_VERBOSE" ]] && unset IS_VERBOSE IS_VERY_VERBOSE || IS_VERBOSE=true; IS_VERY_VERBOSE=true;;
     y) [[ -n "$SKIP_CONFIRM"    ]] && unset SKIP_CONFIRM               || SKIP_CONFIRM=true;;
     h) usage && exit 0;;
-    *) error "Invalid flag.";;
+    *) usage && echo -e "${SCRIPTPATH}:\n${RED}ERROR: Invalid flag.${NC}"
+      exit 1
   esac
 done 2>/dev/null
 shift "$((OPTIND-1))" # explanation https://unix.stackexchange.com/a/214151
diff --git a/bin/utils/dotfiles/dotupdate b/bin/utils/dotfiles/dotupdate
--- a/bin/utils/dotfiles/dotupdate
+++ b/bin/utils/dotfiles/dotupdate
@@ -26,10 +26,29 @@ DOTFILES_LIST=()
 LOG_FILE_DIR="${HOME}/log"
 LOG_FILE="$(date +"%Y-%m-%dT%H:%M:%S")_$(basename -- $0).log"
 
+SCRIPTPATH="$( cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 ; pwd -P )"
+
+# Ansi color code variables
+RED="\e[0;91m"
+BLUE="\e[0;94m"
+GREEN="\e[0;92m"
+YELLOW="\033[1;33m"
+WHITE="\e[0;97m"
+EXPAND_BG="\e[K"
+RED_BG="\e[0;101m${expand_bg}"
+BLUE_BG="\e[0;104m${expand_bg}"
+GREEN_BG="\e[0;102m${expand_bg}"
+YELLOW_BG="\e[0;103m${expand_bg}"
+BOLD="\e[1m"
+ULINE="\e[4m"
+NC="\e[0m" # No/reset color
+
+
 # Source rc file if exist
 if [[ -e "${DOTFILESRC}" ]]; then
   source "${DOTFILESRC}"
 fi
+
 
 # Display help
 usage() {
@@ -61,45 +80,11 @@ while getopts "dsvVyh" opt; do
     V) [[ -n "$IS_VERY_VERBOSE" ]] && unset IS_VERBOSE IS_VERY_VERBOSE || IS_VERBOSE=true; IS_VERY_VERBOSE=true;;
     y) [[ -n "$SKIP_CONFIRM"    ]] && unset SKIP_CONFIRM               || SKIP_CONFIRM=true;;
     h) usage && exit 0;;
-    *) error "Invalid flag.";;
+    *) usage && echo -e "${SCRIPTPATH}:\n${RED}ERROR: Invalid flag.${NC}"
+      exit 1
   esac
 done 2>/dev/null
 shift "$((OPTIND-1))" # explanation https://unix.stackexchange.com/a/214151
-
-
-SCRIPT_PATH="$(realpath -s "${0}")"
-# Strip trailing '/' in DIR path variables
-DOTFILES_DEST_DIR=$(echo ${DOTFILES_DEST_DIR} | sed -r "s,(.*)/$,\1,")
-LOG_FILE_DIR=$(echo ${LOG_FILE_DIR} | sed -r "s,(.*)/$,\1,")
-
-# Log stdout and stderr to $LOG_FILE in $LOG_FILE_DIR
-if [[ -n "${DEBUG}" ]]; then
-  # Strip trailing '/' in LOG_FILE_DIR path and append "/$LOG_FILE"
-  LOG_FILE_PATH="$(echo ${LOG_FILE_DIR} | sed -r "s,(.*)/$,\1,")/${LOG_FILE}"
-  # Create log directory if not existing
-  if [[ ! -d "${LOG_FILE_DIR}" ]]; then
-    mkdir -p "${LOG_FILE_DIR}"
-  fi
-  # Initialize log file
-  echo -e "${SCRIPT_PATH} log outputs\n" > ${LOG_FILE_PATH}
-fi
-
-
-# Ansi color code variables
-# Ref: https://techstop.github.io/bash-script-colors/
-RED="\e[0;91m"
-BLUE="\e[0;94m"
-GREEN="\e[0;92m"
-YELLOW="\033[1;33m"
-WHITE="\e[0;97m"
-EXPAND_BG="\e[K"
-RED_BG="\e[0;101m${expand_bg}"
-BLUE_BG="\e[0;104m${expand_bg}"
-GREEN_BG="\e[0;102m${expand_bg}"
-YELLOW_BG="\e[0;103m${expand_bg}"
-BOLD="\e[1m"
-ULINE="\e[4m"
-NC="\e[0m" # No/reset color
 
 # Stores message into $IN if string argument is passed in, else read from stdin
 # and store it in $IN (used with pipe '|').  Only log message on debug mode.
@@ -172,6 +157,24 @@ error() {
   fi
 }
 
+# Strip trailing '/' in DIR path variables
+DOTFILES_DEST_DIR=$(echo ${DOTFILES_DEST_DIR} | sed 's,/*$,,')
+LOG_FILE_DIR=$(echo ${LOG_FILE_DIR} | sed 's,/*$,,')
+
+# Log stdout and stderr to $LOG_FILE in $LOG_FILE_DIR
+if [[ -n "${DEBUG}" ]]; then
+  # Append LOG_FILE
+  LOG_FILE_PATH="${LOG_FILE_DIR}/${LOG_FILE}"
+  # Create log directory if not existing
+  if [[ ! -d "${LOG_FILE_DIR}" ]]; then
+    mkdir -p "${LOG_FILE_DIR}"
+  fi
+  # Initialize log file
+  echo -e "${SCRIPTPATH} log outputs\n" > ${LOG_FILE_PATH}
+fi
+
+################################# START SCRIPT #################################
+
 # TODO: Make bidirectional
 #       Make diffing changes detect the most recent file
 # Compares two file path (would compare recursively if files are directories).
@@ -187,11 +190,11 @@ error() {
 # $6 = Pass in integer '1' to turn on IS_SILENT
 #
 # Returns $3, $4, $5 variable args with new values from execution.
-cmp_files() {
+detect_changes() {
   local __source=$1
   local __target=$2
   local __changes_list=$3
-  local __detected_count=$4
+  local __changes_count=$4
   local __total_files_count=$5
   local IS_SILENT=$6
 
@@ -204,17 +207,21 @@ cmp_files() {
     echolog "${RED}${FUNCNAME[0]}: Invalid source path \'${__target}\'${NC}" && return 2
 
   local __tmp_changes_list
-  local __tmp_detected_count
+  local __tmp_changes_count
   local __tmp_total_files_count
+
+  # Strip all trailing backslashes '/'
+  __source=$(echo "${__source}" | sed 's,/*$,,')
+  __target=$(echo "${__target}" | sed 's,/*$,,')
 
   if [[ -d "${__source}" ]]; then # Directory dotfile
     # Recursively compare
     while IFS= read -r -d '' __source_file; do
-
+      # Strip all trailing backslashes '/'
+      __source_file=$(echo "${__source_file}" | sed 's,/*$,,')
       # Get relative path
-      __rel_path_file=$(echo "${__source_file}" | sed "s,${__source},,")
+      __rel_path_file=$(echo "${__source_file}" | sed "s,${__source}/,,")
       __target_file="${__target}/${__rel_path_file}"
-
       # Compare dotfiles in destination dir with local copy in home dir
       if cmp -s "${__source_file}" "${__target_file}"; then
         if [[ ${IS_SILENT} -ne 1 ]]; then
@@ -233,7 +240,7 @@ cmp_files() {
           log "${BLUE}TARGET ${__target_file}${NC}"
         fi
         # Record changes
-        __tmp_detected_count=$(expr ${__tmp_detected_count} + 1)
+        __tmp_changes_count=$(expr ${__tmp_changes_count} + 1)
         if [[ -z ${__tmp_changes_list} ]]; then
           __tmp_changes_list="${__source_file};${__target_file}"
         else
@@ -242,7 +249,7 @@ cmp_files() {
       fi
       # Increment total files compared
       __tmp_total_files_count=$(expr ${__tmp_total_files_count} + 1)
-    done < <(find "${__source}" -not -path "*/.git/*" -type f -print0)
+    done < <(find "${__source}" -not -path "*/.git/*" -type f -print0) # Process substitution for outside variables
   else # Non-directory dotfile
     # Compare dotfiles in destination dir with local copy in home dir
     if cmp -s "${__source}" "${__target}"; then
@@ -262,7 +269,7 @@ cmp_files() {
         log "${BLUE}TARGET ${__target}${NC}"
       fi
       # Record changes
-      __tmp_detected_count=$(expr ${__tmp_detected_count} + 1)
+      __tmp_changes_count=$(expr ${__tmp_changes_count} + 1)
       if [[ -z ${__tmp_changes_list} ]]; then
         __tmp_changes_list="${__source};${__target}"
       else
@@ -272,14 +279,115 @@ cmp_files() {
     # Increment total files compared
     __tmp_total_files_count=$(expr ${__tmp_total_files_count} + 1)
   fi
-
   # Return variables
-  [[ -n "${__changes_list}" ]]       && eval $__changes_list="'$__tmp_changes_list'"
-  [[ -n "${__detected_count}" ]]     && eval $__detected_count=$__tmp_detected_count
+  [[ -n "${__changes_list}" ]]      && eval $__changes_list="'$__tmp_changes_list'"
+  [[ -n "${__changes_count}" ]]     && eval $__changes_count=$__tmp_changes_count
   [[ -n "${__total_files_count}" ]] && eval $__total_files_count=$__tmp_total_files_count
 }
 
-total_detected=0
+# TODO:
+# Compares two file path (would compare recursively if files are directories).
+# Require at least 3 arguments or args $1, $2, and $3 to execute.
+#
+# ARGS:
+# $1 = Source file path
+# $2 = Target file path
+# $3 = List of detected changes, including source and target separated by ';',
+#      and delimited by '\n'.
+# $4 = Detected changes count
+# $5 = Total files compared
+# $6 = Pass in integer '1' to turn on IS_SILENT
+#
+# Returns $3, $4, $5 variable args with new values from execution.
+detect_delete() {
+  local __source=$1
+  local __target=$2
+  local __changes_list=$3
+  local __deleted_count=$4
+  local __total_files_count=$5
+  local IS_SILENT=$6
+
+  # Check args count
+  [[ $# -lt 3 ]] && echolog "${RED}${FUNCNAME[0]}: Invalid number of arguments${NC}" && return 1
+  # Exit if invalid path
+  [[ ! -e "${__source}" ]] && \
+    echolog "${RED}${FUNCNAME[0]}: Invalid source path \'${__source}\'${NC}" && return 2
+  [[ ! -e "${__target}" ]] && \
+    echolog "${RED}${FUNCNAME[0]}: Invalid source path \'${__target}\'${NC}" && return 2
+
+  local __tmp_changes_list
+  local __tmp_deleted_count
+  local __tmp_total_files_count
+
+  # Strip all trailing backslashes '/'
+  __source=$(echo "${__source}" | sed 's,/*$,,')
+  __target=$(echo "${__target}" | sed 's,/*$,,')
+
+  if [[ -d "${__source}" ]]; then # Directory dotfile
+    # Recursively compare
+    while IFS= read -r -d '' __source_file; do
+      # Strip all trailing backslashes '/'
+      __source_file=$(echo "${__source_file}" | sed 's,/*$,,')
+      # Get relative path
+      __rel_path_file=$(echo "${__source_file}" | sed "s,${__source}/,,")
+      __target_file="${__target}/${__rel_path_file}"
+      # Check deleted files
+      if [[ -e "${__target_file}" ]]; then
+        if [[ ${IS_SILENT} -ne 1 ]]; then
+          echolog "File exist in ${__target_file}"
+        else
+          log "File exists in ${__target_file}"
+        fi
+      else
+        if [[ ${IS_SILENT} -ne 1 ]]; then
+          echolog "${RED}File to be deleted ${__source_file}${NC}"
+        else
+          log "${RED}File to be deleted ${__source_file}${NC}"
+        fi
+        # Record changes
+        __tmp_deleted_count=$(expr ${__tmp_deleted_count} + 1)
+        if [[ -z ${__tmp_changes_list} ]]; then
+          __tmp_changes_list="${__source_file}"
+        else
+          __tmp_changes_list="${__tmp_changes_list}\n${__source_file}"
+        fi
+      fi
+      # Increment total files compared
+      __tmp_total_files_count=$(expr ${__tmp_total_files_count} + 1)
+    done < <(find "${__source}" -not -path "*/.git/*" -type f -print0) # Process substitution for outside variables
+  else # Non-directory dotfile
+    # Check deleted files
+    if [[ -e "${__target}" ]]; then
+      if [[ ${IS_SILENT} -ne 1 ]]; then
+        echolog "File exist in ${__target}"
+      else
+        log "File exists in ${__target}"
+      fi
+    else
+      if [[ ${IS_SILENT} -ne 1 ]]; then
+        echolog "${RED}File does not exist ${__source}${NC}"
+      else
+        log "${RED}File does not exist ${__source}${NC}"
+      fi
+      # Record changes
+      __tmp_deleted_count=$(expr ${__tmp_deleted_count} + 1)
+      if [[ -z ${__tmp_changes_list} ]]; then
+        __tmp_changes_list="${__source}"
+      else
+        __tmp_changes_list="${__tmp_changes_list}\n${__source}"
+      fi
+    fi
+    # Increment total files compared
+    __tmp_total_files_count=$(expr ${__tmp_total_files_count} + 1)
+  fi
+  # Return variables
+  [[ -n "${__changes_list}" ]]      && eval $__changes_list="'$__tmp_changes_list'"
+  [[ -n "${__deleted_count}" ]]     && eval $__deleted_count=$__tmp_deleted_count
+  [[ -n "${__total_files_count}" ]] && eval $__total_files_count=$__tmp_total_files_count
+}
+
+total_changes_count=0
+total_deleted_count=0
 total_files_count=0
 
 echolog "Detecting dotfiles changes..."
@@ -287,28 +395,41 @@ echolog
 for dotfile in ${DOTFILES_LIST[@]}; do
   # Strip home directory from path
   home_stripped=$(echo "$dotfile" | sed "s,${HOME}/,,")
-  # Strip trailing '/' in directory path
-  home_stripped=$(echo "${home_stripped}" | sed -r "s,(.*)/$,\1,")
 
-  cmp_files "${dotfile}" "${DOTFILES_DEST_DIR}/${home_stripped}" list detected_count files_count
+  detect_changes "${dotfile}" "${DOTFILES_DEST_DIR}/${home_stripped}" changes changes_count files_count
+  detect_delete "${DOTFILES_DEST_DIR}/${home_stripped}" "${dotfile}" delete delete_count
+
+  # Initialize counters if none
+  [[ -z "${changes_count}" ]] && changes_count=0
+  [[ -z "${delete_count}" ]] && delete_count=0
+  [[ -z "${files_count}" ]] && files_count=0
 
   # Update changes list
-  if [[ -n "${list}" ]]; then
+  if [[ -n "${changes}" ]]; then
     if [[ -z ${changes_list} ]]; then
-      changes_list="${list}"
+      changes_list="${changes}"
     else
-      changes_list="${changes_list}\n${list}"
+      changes_list="${changes_list}\n${changes}"
     fi
+    # Increment changes counter
+    total_changes_count=$(expr ${total_changes_count} + ${changes_count})
   fi
-  # Increment counters
-  [[ -z "${detected_count}" ]] && detected_count=0
-  [[ -z "${files_count}" ]] && files_count=0
-  total_detected=$(expr ${total_detected} + ${detected_count})
-  total_files_count=$(expr ${total_files_count} + ${files_count})
+  if [[ -n "${delete}" ]]; then
+    if [[ -z ${changes_list} ]]; then
+      changes_list="${delete}"
+    else
+      changes_list="${changes_list}\n${delete}"
+    fi
+    # Increment delete counter
+    total_deleted_count=$(expr ${total_deleted_count} + ${delete_count})
+  fi
+  # Increment total files counters
+  total_files_count=$(expr ${total_files_count} + ${files_count} + ${delete_count})
 done
 
-# Abort if no dotfiles detected
-[[ ${total_detected} -eq 0 ]] && abort "\nAborting... No dotfiles to backup."
+# Abort if no changes or delete detected
+[[ ${total_changes_count} -eq 0 ]] && [[ ${total_deleted_count} -eq 0 ]] &&
+  abort "\nAborting... No dotfiles to backup."
 
 echolog
 echolog "${ULINE}Files with changes:${NC}"
@@ -322,9 +443,10 @@ while IFS= read -r file_tuple; do
   # Split file_tuple
   IFS=';' read -r -a file_arr <<< "${file_tuple}"
   source_file="${file_arr[0]}"; target_file="${file_arr[1]}"
-
-  if [[ -e "${target_file}" ]]; then # check if target_file not existing
     # Copy source to target file
+  if [[ -z "${target_file}" ]]; then # check if target_file is missing
+    echolog "${RED}-${source_file}${NC}"
+  elif [[ -e "${target_file}" ]]; then # check if target_file not existing
     # Diff source and target file
     if [[ -n "${IS_VERY_VERBOSE}" ]] && [[ -z "${IS_SILENT}" ]]; then
       if command -v colordiff &> /dev/null; then
@@ -341,12 +463,16 @@ while IFS= read -r file_tuple; do
     echolog "${GREEN}+${target_file}${NC}"
     new_files_count=$((new_files_count+1))
   fi
-done < <(echo -e "${changes_list}")
+done < <(echo -e "${changes_list}") # Process substitution for outside variables
 
 echolog
-echolog "Total dotfiles: \t\t${total_files_count}"
-echolog "${YELLOW}Total files with changes: \t${modified_files_count}${NC}"
-echolog "${GREEN}Total new files: \t\t${new_files_count}${NC}"
+echolog "Total dotfiles to updated: \t${total_files_count}"
+[[ ${modified_files_count} -gt 0 ]] &&
+  echolog "${YELLOW}Total changed files: \t${modified_files_count}${NC}"
+[[ ${new_files_count} -gt 0 ]] &&
+  echolog "${GREEN}Total new files: \t${new_files_count}${NC}"
+[[ ${total_deleted_count} -gt 0 ]] &&
+  echolog "${RED}Total delete files: \t${total_deleted_count}${NC}"
 echolog
 
 
@@ -362,16 +488,18 @@ if [[ -z "${SKIP_CONFIRM}" ]]; then
   fi
 fi
 
-# Copy changes to destination directory
+# Copy changes to destination directory and delete missing files
 echo -e "${changes_list}" | while IFS= read -r file_tuple; do
   IFS=';' read -r -a file_arr <<< "$file_tuple"
   source_file="${file_arr[0]}"; target_file="${file_arr[1]}"
   target_dir="$(dirname "${target_file}")"
-  if [[ -d "${target_dir}" ]]; then
-    cp -rL ${source_file} ${target_file} | log
-  else # Create target_dir if not existing
+  if [[ -z "${target_file}" ]]; then # check if target_file is missing
+    rm -v "${source_file}" | log
+  elif [[ -d "${target_dir}" ]]; then # Check target dir path
+    cp -rLv ${source_file} ${target_file} | log
+  else # Create target dir if not existing
     mkdir -p "${target_dir}"
-    cp -rL ${source_file} ${target_file} | log
+    cp -rLv ${source_file} ${target_file} | log
   fi
 done
 
@@ -379,12 +507,12 @@ done
 for dotfile in ${DOTFILES_LIST[@]}; do
   # Strip home directory from path
   home_stripped=$(echo "$dotfile" | sed "s,${HOME}/,,")
-  # Strip trailing '/' in directory path
-  home_stripped=$(echo "${home_stripped}" | sed -r "s,(.*)/$,\1,")
 
-  cmp_files "${dotfile}" "${DOTFILES_DEST_DIR}/${home_stripped}" list changes_count files_count 1
+  detect_changes "${dotfile}" "${DOTFILES_DEST_DIR}/${home_stripped}" changes changes_count files_count
+  detect_delete "${DOTFILES_DEST_DIR}/${home_stripped}" "${dotfile}" delete delete_count
 
-  [[ ${changes_count} -gt 0 ]] && error "Dotupdate failed. Changes persists" 1
+  [[ ${changes_count} -gt 0 ]] || [[ ${delete_count} -gt 0 ]] &&
+    error "Dotupdate failed. Changes persists" 1
 done
 
 ok "Dotfiles update successful!"
