Integrate utils and delegated detect functions

diff --git a/bin/utils/dotfiles/dotbackup b/bin/utils/dotfiles/dotbackup
--- a/bin/utils/dotfiles/dotbackup
+++ b/bin/utils/dotfiles/dotbackup
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+################################################################################
 # Backs up all specified dotfiles from DOTFILES_LIST into DOTFILES_BACKUP_DIR
 # within a current timestamp named directory.
 #
@@ -21,9 +22,12 @@
 #                                 mode. Defaults to current timestamp.
 #
 ################################################################################
-#
 # Author : Mark Lucernas <https://github.com/marklcrns>
 # Date   : 2020-08-02
+################################################################################
+
+
+
 
 
 ################################################## CONSTANT GLOBAL VARIABLES ###
@@ -39,26 +43,25 @@ LOG_FILE="$(date +"%Y-%m-%dT%H:%M:%S")_$(basename -- $0).log"
 
 SCRIPTPATH="$(realpath -s $0)"
 
-# Ansi color code variables
-RED="\e[0;91m"
-BLUE="\e[0;94m"
-GREEN="\e[0;92m"
-YELLOW="\033[1;33m"
-WHITE="\e[0;97m"
-EXPAND_BG="\e[K"
-RED_BG="\e[0;101m${expand_bg}"
-BLUE_BG="\e[0;104m${expand_bg}"
-GREEN_BG="\e[0;102m${expand_bg}"
-YELLOW_BG="\e[0;103m${expand_bg}"
-BOLD="\e[1m"
-ULINE="\e[4m"
-NC="\e[0m" # No/reset color
+############################################## EXTERNAL DEPENDENCIES SCRIPTS ###
 
+# Ansi color code variables
+if [[ -e "../../scripting-utils/colors" ]]; then
+  source ../../scripting-utils/colors
+else
+  echo "${SCRIPTPATH} WARNING: Failed to source \'../../scripting-utils/colors\' dependency"
+  echo
+fi
+# Utility functions
+if [[ -e "../../scripting-utils/utils" ]]; then
+  source ../../scripting-utils/utils
+else
+  echo "${SCRIPTPATH} ERROR: Failed to source \'../../scripting-utils/utils\' dependency"
+  exit 1
+fi
 
 # Source rc file if exist
-if [[ -e "${DOTFILESRC}" ]]; then
-  source "${DOTFILESRC}"
-fi
+[[ -e "${DOTFILESRC}" ]] && source "${DOTFILESRC}"
 
 ############################################################### FLAG OPTIONS ###
 
@@ -70,13 +73,13 @@ USAGE:
 Backs up all specified dotfiles from DOTFILES_LIST into DOTFILES_BACKUP_DIR
 within a current timestamp named directory.
 
-  dotbackup [ -adsvVy ] [ -A backups-limit ]
+  dotbackup [ -aDsvVy ] [ -A backups-limit ]
 
 OPTIONS:
 
    -a : auto clean old backups if greater than default limit
    -A : auto clean old backups if greater than specified limit
-   -d : debug mode (redirect output in log file)
+   -D : debug mode (redirect output in log file)
    -s : silent
    -v : verbose
    -V : very verbose
@@ -87,11 +90,11 @@ EOF
 }
 
 # Set flag options
-while getopts "aA:dsvVyh" opt; do
+while getopts "aA:DsvVyh" opt; do
   case "$opt" in
     a) [[ -n "$AUTO_CLEAN"      ]] && unset AUTO_CLEAN                 || AUTO_CLEAN=true;;
     A) [[ -n "$AUTO_CLEAN"      ]] && unset AUTO_CLEAN                 || AUTO_CLEAN=true; DOTFILES_BACKUP_LIMIT="${OPTARG}";;
-    d) [[ -n "$DEBUG"           ]] && unset DEBUG                      || DEBUG=true;;
+    D) [[ -n "$DEBUG"           ]] && unset DEBUG                      || DEBUG=true;;
     s) [[ -n "$IS_SILENT"       ]] && unset IS_SILENT                  || IS_SILENT=true;;
     v) [[ -n "$IS_VERBOSE"      ]] && unset IS_VERBOSE                 || IS_VERBOSE=true;;
     V) [[ -n "$IS_VERY_VERBOSE" ]] && unset IS_VERBOSE IS_VERY_VERBOSE || IS_VERBOSE=true; IS_VERY_VERBOSE=true;;
@@ -102,172 +105,6 @@ while getopts "aA:dsvVyh" opt; do
   esac
 done 2>/dev/null
 shift "$((OPTIND-1))" # explanation https://unix.stackexchange.com/a/214151
-
-########################################################## UTILITY FUNCTIONS ###
-
-# Log message into LOG_FILE_PATH. Can be used with pipeline '|' to log message
-# from stdout.
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-# Echo message if IS_VERY_VERBOSE
-log() {
-  message=$1
-  force_silent=$2
-  if [[ -n "$message" ]]; then
-    IN="$message"
-    [[ -n "${DEBUG}" ]] && echo -e "${IN}" >> "${LOG_FILE_PATH}"
-  else
-    read IN
-    if [[ -n ${IN} ]]; then
-      [[ -n "${DEBUG}" ]] && echo -e "${IN}" >> "${LOG_FILE_PATH}"
-    fi
-    # Echo log message if IS_VERY_VERBOSE
-    if [[ -n "${IS_VERY_VERBOSE}" ]]; then
-      [[ ${force_silent} -ne 1 ]] && echo -e "$message" # Skip message if force_silent
-    fi
-  fi
-}
-
-# Echo message and log into LOG_FILE_PATH.
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-echolog(){
-  message=$1
-  force_silent=$2
-  if [[ -n "${message}" ]]; then
-    # echo if verbose
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "${message}"
-    # Log message on debug mode
-    [[ -n "${DEBUG}" ]] && echo -e "${message}" >> "${LOG_FILE_PATH}"
-  else # Print newline if no message
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e ""
-    [[ -n "${DEBUG}" ]] && echo -e "" >> "${LOG_FILE_PATH}"
-  fi
-}
-
-# Execute command string with `eval` then log into LOG_FILE_PATH
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-# Echo message if IS_VERBOSE
-execlog() {
-  command_string=$1
-  force_silent=$2
-  if [[ -n "${command_string}" ]]; then
-    # echo if verbose
-    [[ -n "${IS_VERBOSE}" ]] && [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "${command_string}"
-    # Log command_string on debug mode
-    [[ -n "${DEBUG}" ]] && echo -e "${command_string}" >> "${LOG_FILE_PATH}"
-    # execute command
-    if eval "${command_string}"; then
-      return 0
-    else
-      # echo if verbose
-      [[ -n "${IS_VERBOSE}" ]] && [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-        echo -e "${RED}${FUNCNAME[0]}(): Command \'${command_string}\' failed${NC}"
-      # Log command_string on debug mode
-      [[ -n "${DEBUG}" ]] &&
-        echo -e "${FUNCNAME[0]}(): Command \'${command_string}\' failed" >> "${LOG_FILE_PATH}"
-      return 1
-    fi
-  else
-    # Return error if no command given
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "${RED}${FUNCNAME[0]}(): Command not found${NC}"
-    [[ -n "${DEBUG}" ]] &&
-      echo -e "${FUNCNAME[0]}: Command not found" >> "${LOG_FILE_PATH}"
-    return 1
-  fi
-}
-
-# Echo message in GREEN characters
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-ok() {
-  message=$1
-  force_silent=$2
-  if [[ -n "${message}" ]]; then
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "${GREEN}${message}${NC}"
-    # Log message on debug mode
-    [[ -n "${DEBUG}" ]] && echo -e "${message}" >> "${LOG_FILE_PATH}"
-  fi
-}
-
-# Echo message in YELLOW characters
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-warning() {
-  message=$1
-  force_silent=$2
-  if [[ -n "${message}" ]]; then
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "${YELLOW}${message}${NC}"
-    # Log message on debug mode
-    [[ -n "${DEBUG}" ]] && echo -e "${message}" >> "${LOG_FILE_PATH}"
-  fi
-}
-
-# Echo message in YELLOW characters and `exit` script with exit code 1
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-abort() {
-  message=$1
-  force_silent=$2
-  if [[ -n "${message}" ]]; then
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "${YELLOW}${message}${NC}"
-    # Log message on debug mode
-    [[ -n "${DEBUG}" ]] && echo -e "${message}" >> "${LOG_FILE_PATH}"
-  fi
-  exit 1
-}
-
-# Echo message in RED characters and `exit` script with exit code 1.
-# Second argument accepts integer to override default exit code.
-# Third argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-error() {
-  message=$1
-  exit_code=$2
-  force_silent=$3
-  if [[ -n "${message}" ]]; then
-    if [[ -n ${exit_code} ]]; then # Remove SCRIPTPATH if no exit code
-      [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-        echo -e "${RED}\n${SCRIPTPATH}: ${message}${NC}"
-    else
-      [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-        echo -e "${RED}${message}${NC}"
-    fi
-    # Log message on debug mode
-    if [[ -n ${exit_code} ]]; then # Remove SCRIPTPATH if no exit code
-      [[ -n "${DEBUG}" ]] && echo -e "\n${SCRIPTPATH}: ${message}" >> "${LOG_FILE_PATH}"
-    else
-      [[ -n "${DEBUG}" ]] && echo -e "${message}" >> "${LOG_FILE_PATH}"
-    fi
-  fi
-  # Exit with specified exit code. Do not exit if no exit code
-  if [[ -n ${exit_code} ]]; then
-    [[ ${exit_code} -ge 0 ]] && exit ${exit_code}
-  fi
-}
-
-# Echo message in GREEN characters and `exit` with exit code 0
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-finish() {
-  message=$1
-  force_silent=$2
-  if [[ -n "${message}" ]]; then
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "\n${message}"
-    # Log message on debug mode
-    [[ -n "${DEBUG}" ]] && echo -e "\n${message}" >> "${LOG_FILE_PATH}"
-  fi
-  exit 0
-}
 
 ####################################################### PRE-EXECUTION SET UP ###
 
@@ -287,6 +124,8 @@ if [[ -n "${DEBUG}" ]]; then
   # Initialize log file
   echo -e "${SCRIPTPATH} log outputs\n" > ${LOG_FILE_PATH}
 fi
+
+################################################## SCRIPT ARGUMENTS HANDLING ###
 
 ########################################################## SCRIPT EXECUTIONS ###
 
diff --git a/bin/utils/dotfiles/dotdist b/bin/utils/dotfiles/dotdist
--- a/bin/utils/dotfiles/dotdist
+++ b/bin/utils/dotfiles/dotdist
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+################################################################################
 # Distribute all specified dotfiles in DOTFILES_LIST from DOTFILES_TARGET_DIR
 # into DOTFILES_SOURCE_DIR.
 # Uses `cmp` to compare files and `diff -c` to display changes when `-V` flag is
@@ -19,9 +20,12 @@
 #                       Defaults to current timestamp.
 #
 ################################################################################
-#
 # Author : Mark Lucernas <https://github.com/marklcrns>
 # Date   : 2020-08-05
+################################################################################
+
+
+
 
 
 ################################################## CONSTANT GLOBAL VARIABLES ###
@@ -35,26 +39,33 @@ LOG_FILE="$(date +"%Y-%m-%dT%H:%M:%S")_$(basename -- $0).log"
 
 SCRIPTPATH="$(realpath -s $0)"
 
-# Ansi color code variables
-RED="\e[0;91m"
-BLUE="\e[0;94m"
-GREEN="\e[0;92m"
-YELLOW="\033[1;33m"
-WHITE="\e[0;97m"
-EXPAND_BG="\e[K"
-RED_BG="\e[0;101m${expand_bg}"
-BLUE_BG="\e[0;104m${expand_bg}"
-GREEN_BG="\e[0;102m${expand_bg}"
-YELLOW_BG="\e[0;103m${expand_bg}"
-BOLD="\e[1m"
-ULINE="\e[4m"
-NC="\e[0m" # No/reset color
+############################################## EXTERNAL DEPENDENCIES SCRIPTS ###
 
+# Ansi color code variables
+if [[ -e "../../scripting-utils/colors" ]]; then
+  source ../../scripting-utils/colors
+else
+  echo "${SCRIPTPATH} WARNING: Failed to source \'../../scripting-utils/colors\' dependency"
+  echo
+fi
+# Utility functions
+if [[ -e "../../scripting-utils/utils" ]]; then
+  source ../../scripting-utils/utils
+else
+  echo "${SCRIPTPATH} ERROR: Failed to source \'../../scripting-utils/utils\' dependency"
+  exit 1
+fi
+
+# Detect utility for changes and deletion detection
+if [[ -e "./detect" ]]; then
+  source ./detect
+else
+  echo "${SCRIPTPATH} ERROR: Failed to source \'./detect\' dependency"
+  exit 1
+fi
 
 # Source rc file if exist
-if [[ -e "${DOTFILESRC}" ]]; then
-  source "${DOTFILESRC}"
-fi
+[[ -e "${DOTFILESRC}" ]] && source "${DOTFILESRC}"
 
 ############################################################### FLAG OPTIONS ###
 
@@ -66,12 +77,13 @@ USAGE:
 Distribute all specified dotfiles in DOTFILES_LIST from DOTFILES_TARGET_DIR
 into DOTFILES_SOURCE_DIR.
 
-  dotdist [ -bdsvVy ]
+  dotdist [ -bdDsvVy ]
 
 OPTIONS:
 
    -b : backup files
-   -d : debug mode (redirect output in log file)
+   -d : skip file deletion
+   -D : debug mode (redirect output in log file)
    -s : silent
    -v : verbose
    -V : very verbose
@@ -82,10 +94,11 @@ EOF
 }
 
 # Set flag options
-while getopts "bdsvVyh" opt; do
+while getopts "bdDsvVyh" opt; do
   case "$opt" in
     b) [[ -n "$IS_BACKUP"       ]] && unset IS_BACKUP                  || IS_BACKUP=true;;
-    d) [[ -n "$DEBUG"           ]] && unset DEBUG                      || DEBUG=true;;
+    d) [[ -n "$NO_DELETE"       ]] && unset NO_DELETE                  || NO_DELETE=true;;
+    D) [[ -n "$DEBUG"           ]] && unset DEBUG                      || DEBUG=true;;
     s) [[ -n "$IS_SILENT"       ]] && unset IS_SILENT                  || IS_SILENT=true;;
     v) [[ -n "$IS_VERBOSE"      ]] && unset IS_VERBOSE                 || IS_VERBOSE=true;;
     V) [[ -n "$IS_VERY_VERBOSE" ]] && unset IS_VERBOSE IS_VERY_VERBOSE || IS_VERBOSE=true; IS_VERY_VERBOSE=true;;
@@ -97,171 +110,6 @@ while getopts "bdsvVyh" opt; do
 done 2>/dev/null
 shift "$((OPTIND-1))" # explanation https://unix.stackexchange.com/a/214151
 
-########################################################## UTILITY FUNCTIONS ###
-
-# Log message into LOG_FILE_PATH. Can be used with pipeline '|' to log message
-# from stdout.
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-# Echo message if IS_VERY_VERBOSE
-log() {
-  message=$1
-  force_silent=$2
-  if [[ -n "$message" ]]; then
-    IN="$message"
-    [[ -n "${DEBUG}" ]] && echo -e "${IN}" >> "${LOG_FILE_PATH}"
-  else
-    read IN
-    if [[ -n ${IN} ]]; then
-      [[ -n "${DEBUG}" ]] && echo -e "${IN}" >> "${LOG_FILE_PATH}"
-    fi
-    # Echo log message if IS_VERY_VERBOSE
-    if [[ -n "${IS_VERY_VERBOSE}" ]]; then
-      [[ ${force_silent} -ne 1 ]] && echo -e "$message" # Skip message if force_silent
-    fi
-  fi
-}
-
-# Echo message and log into LOG_FILE_PATH.
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-echolog(){
-  message=$1
-  force_silent=$2
-  if [[ -n "${message}" ]]; then
-    # echo if verbose
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "${message}"
-    # Log message on debug mode
-    [[ -n "${DEBUG}" ]] && echo -e "${message}" >> "${LOG_FILE_PATH}"
-  else # Print newline if no message
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e ""
-    [[ -n "${DEBUG}" ]] && echo -e "" >> "${LOG_FILE_PATH}"
-  fi
-}
-
-# Execute command string with `eval` then log into LOG_FILE_PATH
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-# Echo message if IS_VERBOSE
-execlog() {
-  command_string=$1
-  force_silent=$2
-  if [[ -n "${command_string}" ]]; then
-    # echo if verbose
-    [[ -n "${IS_VERBOSE}" ]] && [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "${command_string}"
-    # Log command_string on debug mode
-    [[ -n "${DEBUG}" ]] && echo -e "${command_string}" >> "${LOG_FILE_PATH}"
-    # execute command
-    if eval "${command_string}"; then
-      return 0
-    else
-      # echo if verbose
-      [[ -n "${IS_VERBOSE}" ]] && [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-        echo -e "${RED}${FUNCNAME[0]}(): Command \'${command_string}\' failed${NC}"
-      # Log command_string on debug mode
-      [[ -n "${DEBUG}" ]] &&
-        echo -e "${FUNCNAME[0]}(): Command \'${command_string}\' failed" >> "${LOG_FILE_PATH}"
-      return 1
-    fi
-  else
-    # Return error if no command given
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "${RED}${FUNCNAME[0]}(): Command not found${NC}"
-    [[ -n "${DEBUG}" ]] &&
-      echo -e "${FUNCNAME[0]}: Command not found" >> "${LOG_FILE_PATH}"
-    return 1
-  fi
-}
-
-# Echo message in GREEN characters
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-ok() {
-  message=$1
-  force_silent=$2
-  if [[ -n "${message}" ]]; then
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "${GREEN}${message}${NC}"
-    # Log message on debug mode
-    [[ -n "${DEBUG}" ]] && echo -e "${message}" >> "${LOG_FILE_PATH}"
-  fi
-}
-
-# Echo message in YELLOW characters
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-warning() {
-  message=$1
-  force_silent=$2
-  if [[ -n "${message}" ]]; then
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "${YELLOW}${message}${NC}"
-    # Log message on debug mode
-    [[ -n "${DEBUG}" ]] && echo -e "${message}" >> "${LOG_FILE_PATH}"
-  fi
-}
-
-# Echo message in YELLOW characters and `exit` script with exit code 1
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-abort() {
-  message=$1
-  force_silent=$2
-  if [[ -n "${message}" ]]; then
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "${YELLOW}${message}${NC}"
-    # Log message on debug mode
-    [[ -n "${DEBUG}" ]] && echo -e "${message}" >> "${LOG_FILE_PATH}"
-  fi
-  exit 1
-}
-
-# Echo message in RED characters and `exit` script with exit code 1.
-# Second argument accepts integer to override default exit code.
-# Third argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-error() {
-  message=$1
-  exit_code=$2
-  force_silent=$3
-  if [[ -n "${message}" ]]; then
-    if [[ -n ${exit_code} ]]; then # Remove SCRIPTPATH if no exit code
-      [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-        echo -e "${RED}\n${SCRIPTPATH}: ${message}${NC}"
-    else
-      [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-        echo -e "${RED}${message}${NC}"
-    fi
-    # Log message on debug mode
-    if [[ -n ${exit_code} ]]; then # Remove SCRIPTPATH if no exit code
-      [[ -n "${DEBUG}" ]] && echo -e "\n${SCRIPTPATH}: ${message}" >> "${LOG_FILE_PATH}"
-    else
-      [[ -n "${DEBUG}" ]] && echo -e "${message}" >> "${LOG_FILE_PATH}"
-    fi
-  fi
-  # Exit with specified exit code. Do not exit if no exit code
-  if [[ -n ${exit_code} ]]; then
-    [[ ${exit_code} -ge 0 ]] && exit ${exit_code}
-  fi
-}
-
-# Echo message in GREEN characters and `exit` with exit code 0
-# Second argument accepts integer value of 1 only to force silent.
-# Logs message on DEBUG.
-finish() {
-  message=$1
-  force_silent=$2
-  if [[ -n "${message}" ]]; then
-    [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]] &&
-      echo -e "\n${message}"
-    # Log message on debug mode
-    [[ -n "${DEBUG}" ]] && echo -e "\n${message}" >> "${LOG_FILE_PATH}"
-  fi
-  exit 0
-}
 
 ####################################################### PRE-EXECUTION SET UP ###
 
@@ -281,6 +129,8 @@ if [[ -n "${DEBUG}" ]]; then
   # Initialize log file
   echo -e "${SCRIPTPATH} log outputs\n" > ${LOG_FILE_PATH}
 fi
+
+################################################## SCRIPT ARGUMENTS HANDLING ###
 
 ########################################################## SCRIPT EXECUTIONS ###
 
@@ -438,8 +288,11 @@ detect_delete() {
         echolog "File exist in ${__target_file}" ${silent}
       else
         echolog "${RED}File to be deleted ${__source_file}${NC}" ${silent}
-        # Record changes
-        __tmp_deleted_count=$(expr ${__tmp_deleted_count} + 1)
+        # Record deletion if not NO_DELETE
+        if [[ -z "${NO_DELETE}" ]]; then
+          __tmp_deleted_count=$(expr ${__tmp_deleted_count} + 1)
+        fi
+        # Append to changes list
         if [[ -z ${__tmp_changes_list} ]]; then
           __tmp_changes_list="${__source_file}"
         else
@@ -531,7 +384,11 @@ while IFS= read -r file_tuple; do
   source_file="${file_arr[0]}"; target_file="${file_arr[1]}"
   # Copy source to target file
   if [[ -z "${target_file}" ]]; then # check if target_file is missing
-    echolog "${RED}-${source_file}${NC}"
+    if [[ -z "${NO_DELETE}" ]]; then
+      echolog "${RED}-${source_file}${NC}"
+    else
+      echolog "${RED}-${source_file} ${YELLOW}SKIPPED${NC}"
+    fi
   elif [[ -e "${target_file}" ]]; then # check if target_file not existing
     # Diff source and target file
     if [[ -n "${IS_VERY_VERBOSE}" ]] && [[ -z "${IS_SILENT}" ]]; then
@@ -601,10 +458,14 @@ echo -e "${changes_list}" | while IFS= read -r file_tuple; do
   source_file="${file_arr[0]}"; target_file="${file_arr[1]}"
   target_dir="$(dirname "${target_file}")"
   if [[ -z "${target_file}" ]]; then # check if target_file is missing
-    if execlog "rm -f ${source_file}" 1; then
-      ok "${source_file} deleted"
+    if [[ -z "${NO_DELETE}" ]]; then
+      if execlog "rm -f ${source_file}" 1; then
+        ok "${source_file} deleted"
+      else
+        error "Failed to delete ${source_file}"
+      fi
     else
-      error "Failed to delete ${source_file}"
+      warning "Skipping ${source_file} deletion..."
     fi
   elif [[ -d "${target_dir}" ]]; then # Check target dir path
     if execlog "cp -rL ${source_file} ${target_file}" 1; then
@@ -630,7 +491,9 @@ for dotfile in ${DOTFILES_LIST[@]}; do
   source_stripped=$(echo "$dotfile" | sed "s,${DOTFILES_SOURCE_DIR}/,,")
 
   detect_changes "${DOTFILES_TARGET_DIR}/${source_stripped}" "${dotfile}" changes changes_count files_count 1
-  detect_delete "${dotfile}" "${DOTFILES_TARGET_DIR}/${source_stripped}" delete delete_count files_count 1
+  if [[ -z ${NO_DELETE} ]]; then
+    detect_delete "${dotfile}" "${DOTFILES_TARGET_DIR}/${source_stripped}" delete delete_count files_count 1
+  fi
 done
 
 # Catch final check errors
