Update dotfiles scripts

diff --git a/bin/utils/dotfiles/dotbackup b/bin/utils/dotfiles/dotbackup
--- a/bin/utils/dotfiles/dotbackup
+++ b/bin/utils/dotfiles/dotbackup
@@ -291,5 +291,8 @@ if [[ -n "${AUTO_CLEAN}" ]]; then
   fi
 fi
 
+# Catch if dotclearbak failed
+[[ $? -ne 0 ]] && error "Failed to clear backup files" $?
+
 finish "${DOTFILES_BACKUP_DIR}/${BACKUP_DIR_NAME} backup created!"
 
diff --git a/bin/utils/dotfiles/dotdist b/bin/utils/dotfiles/dotdist
--- a/bin/utils/dotfiles/dotdist
+++ b/bin/utils/dotfiles/dotdist
@@ -523,6 +523,9 @@ if [[ -n "${IS_BACKUP}" ]]; then
   fi
 fi
 
+# Catch if dotbackup failed
+[[ $? -ne 0 ]] && error "Failed to backup files" $?
+
 echolog
 echolog "Distributing dotfiles..."
 echolog
