Implement and integrate cleanlog() in utils script

diff --git a/bin/scripting-utils/utils b/bin/scripting-utils/utils
--- a/bin/scripting-utils/utils
+++ b/bin/scripting-utils/utils
@@ -8,15 +8,17 @@
 #
 ################################# Functions ###################################
 #
-# log()     = Log message parameter into LOG_FILE_PATH.
-# echolog() = Echo message and log into LOG_FILE_PATH.
-# execlog() = Execute string command with `eval` and log into LOG_FILE_PATH.
-# ok()      = Echo message in GREEN characters.
-# finish    = Echo message in GREEN characters and exit with 0 exit code.
-# warning() = Echo message in YELLOW characters.
-# abort()   = Echo message in YELLOW characters and exit with 1 exit code.
-# error()   = Echo message in RED characters and exit with 1 exit code by
-#             default. Also accepts integer to override default exit code.
+# log()      = Log message parameter into LOG_FILE_PATH.
+# echolog()  = Echo message and log into LOG_FILE_PATH.
+# execlog()  = Execute string command with `eval` and log into LOG_FILE_PATH.
+# ok()       = Echo message in GREEN characters.
+# finish     = Echo message in GREEN characters and exit with 0 exit code.
+# warning()  = Echo message in YELLOW characters.
+# abort()    = Echo message in YELLOW characters and exit with 1 exit code.
+# error()    = Echo message in RED characters and exit with 1 exit code by
+#              default. Also accepts integer to override default exit code.
+# cleanlog() = Clean oldest excess log files if exceeds $1 (limit) integer
+#              argument.
 #
 # NOTE: All functions has force_silent local variable to disable function
 # outputs.
@@ -24,6 +26,7 @@
 ########################### Script Global Variables ############################
 #
 # DEBUG           = Enables logging of all log functions.
+# LOG_FILE_DIR    = Log file directory path
 # LOG_FILE_PATH   = Log file destination path.
 # IS_SILENT       = Disables output of all functions.
 # IS_VERY_VERBOSE = Enables output of log() function.
@@ -54,7 +57,7 @@ fi
 
 # Log message into LOG_FILE_PATH. Can be used with pipeline '|' to log message
 # from stdout.
-# Second argument accepts integer value of 1 only to force silent.
+# $2 argument accepts only integer value of 1 to force silent.
 # Logs message on DEBUG.
 # Echo message if IS_VERY_VERBOSE
 function log() {
@@ -76,7 +79,7 @@ function log() {
 }
 
 # Echo message and log into LOG_FILE_PATH.
-# Second argument accepts integer value of 1 only to force silent.
+# $2 argument accepts only integer value of 1 to force silent.
 # Logs message on DEBUG.
 function echolog(){
   message=$1
@@ -95,7 +98,7 @@ function echolog(){
 }
 
 # Execute command string with `eval` then log into LOG_FILE_PATH
-# Second argument accepts integer value of 1 only to force silent.
+# $2 argument accepts only integer value of 1 to force silent.
 # Logs message on DEBUG.
 # Echo message if IS_VERBOSE
 function execlog() {
@@ -130,7 +133,7 @@ function execlog() {
 }
 
 # Echo message in GREEN characters
-# Second argument accepts integer value of 1 only to force silent.
+# $2 argument accepts only integer value of 1 to force silent.
 # Logs message on DEBUG.
 function ok() {
   message=$1
@@ -144,7 +147,7 @@ function ok() {
 }
 
 # Echo message in YELLOW characters
-# Second argument accepts integer value of 1 only to force silent.
+# $2 argument accepts only integer value of 1 to force silent.
 # Logs message on DEBUG.
 function warning() {
   message=$1
@@ -158,7 +161,7 @@ function warning() {
 }
 
 # Echo message in YELLOW characters and `exit` script with exit code 1
-# Second argument accepts integer value of 1 only to force silent.
+# $2 argument accepts only integer value of 1 to force silent.
 # Logs message on DEBUG.
 function abort() {
   message=$1
@@ -173,8 +176,8 @@ function abort() {
 }
 
 # Echo message in RED characters and `exit` script with exit code 1.
-# Second argument accepts integer to override default exit code.
-# Third argument accepts integer value of 1 only to force silent.
+# $2 argument accepts integer to override default exit code.
+# $3 argument accepts only integer value of 1 to force silent.
 # Logs message on DEBUG.
 function error() {
   message=$1
@@ -202,7 +205,7 @@ function error() {
 }
 
 # Echo message in GREEN characters and `exit` with exit code 0
-# Second argument accepts integer value of 1 only to force silent.
+# $2 argument accepts only integer value of 1 to force silent.
 # Logs message on DEBUG.
 function finish() {
   message=$1
@@ -214,6 +217,132 @@ function finish() {
     [[ -n "${DEBUG}" ]] && echo -e "\n${message}" >> "${LOG_FILE_PATH}"
   fi
   exit 0
+}
+
+# Clean excess log files in LOG_FILE_DIR exceeding $1 (limit) integer argument.
+# $2 argument accepts only integer value of 1 to force silent.
+# Logs message on DEBUG.
+function cleanlog() {
+  limit=$1
+  force_silent=$2
+
+  # Check if LOG_FILE_DIR is valid
+  if [[ ! -e "${LOG_FILE_DIR}" ]]; then
+    echo -e "${RED}\n${SCRIPTPATH}: LOG_FILE_DIR not specified. Skipping cleaning...${NC}"
+    if [[ -n "${DEBUG}" ]]; then
+      echo -e "\n${SCRIPTPATH}: LOG_FILE_DIR not specified. Skipping cleaning..." >> "${LOG_FILE_PATH}"
+    fi
+    return 1
+  fi
+  if [[ ! -d "${LOG_FILE_DIR}" ]]; then
+    echo -e "${RED}\n${SCRIPTPATH}: Invalid backup directory path${NC}"
+    if [[ -n "${DEBUG}" ]]; then
+      echo -e "${RED}\n${SCRIPTPATH}: Invalid backup directory path${NC}" >> "${LOG_FILE_PATH}"
+    fi
+    exit 1
+  fi
+
+  # Set default limit if not specified
+  [[ -z ${limit} ]] && limit=1000
+
+  # Assess backups to be be removed
+  log_file_count=$(ls "${LOG_FILE_DIR}" | wc -l)
+  to_remove_count=$(( ${log_file_count} - ${limit} ))
+
+  # Cache backup directories to be removed
+  if [[ ${to_remove_count} -lt 0 ]]; then
+    to_remove_count=${log_file_count}
+  fi
+
+  # Get total log files to delete
+  if [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]]; then
+    echo -e "${UL_NC}Removing excess log files:${NC}"
+    echo
+    echo -e "Total log files: \t\t${log_file_count}"
+    echo -e "Oldest log files to remove: \t${to_remove_count}"
+    echo -e "Limit: \t\t\t\t${limit}"
+    echo
+  fi
+  if [[ -n "${DEBUG}" ]]; then
+    echo -e "Removing excess log files:" >> "${LOG_FILE_PATH}"
+    echo "" >> "${LOG_FILE_PATH}"
+    echo -e "Total log files: \t\t\t${backup_dir_count}" >> "${LOG_FILE_PATH}"
+    echo -e "Oldest log files to remove: \t${to_remove_count}" >> "${LOG_FILE_PATH}"
+    echo "" >> "${LOG_FILE_PATH}"
+  fi
+
+  # Abort if log files count is below limit
+  if [[ ${to_remove_count} -eq 0 ]]; then # Abort if nothing to delete
+    if [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]]; then
+      echo -e "No log files to delete."
+    fi
+    if [[ -n "${DEBUG}" ]]; then
+      echo -e "No log files to delete." >> "${LOG_FILE_PATH}"
+    fi
+    return 0
+  elif [[ ${log_file_count} -lt ${limit} ]]; then # Abort if still below limit
+    if [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]]; then
+      echo -e "Log files still below limit. Skipping..."
+    fi
+    if [[ -n "${DEBUG}" ]]; then
+      echo -e "Log files still below limit. Skipping..." >> "${LOG_FILE_PATH}"
+    fi
+    return 0
+  fi
+
+  if [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]]; then
+    echo -e "Removing excess backups..."
+    echo
+  fi
+  if [[ -n "${DEBUG}" ]]; then
+    echo -e "Removing excess backups..." >> "${LOG_FILE_PATH}"
+  fi
+
+  # Get oldest log files amount based on limit
+  to_remove_list="$(ls -1 ${LOG_FILE_DIR} | head -${to_remove_count})"
+  removed_count=0
+  # Execute log file removal
+  while IFS= read -r log_file; do
+    if rm -rf ${LOG_FILE_DIR}/${log_file}; then
+      if [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]]; then
+        echo -e "${YELLOW}${LOG_FILE_DIR}/${log_file} deleted${NC}"
+      fi
+      if [[ -n "${DEBUG}" ]]; then
+        echo -e "${LOG_FILE_DIR}/${log_file} deleted" >> "${LOG_FILE_PATH}"
+      fi
+      # Increment removed count
+      removed_count=$((removed_count+1))
+    else
+      if [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]]; then
+        echo -e "${RED}Failed to remove ${LOG_FILE_DIR}/${log_file}${NC}"
+      fi
+      if [[ -n "${DEBUG}" ]]; then
+        echo -e "Failed to remove ${LOG_FILE_DIR}/${log_file}" >> "${LOG_FILE_PATH}"
+      fi
+    fi
+  done <<< "${to_remove_list}"
+
+  # Final check
+  new_backup_dir_count=$(ls "${LOG_FILE_DIR}" | wc -l)
+  # Check if all log files due for deletion are deleted
+  if [[ $(( ${new_backup_dir_count} + ${removed_count} )) -eq ${log_file_count} ]]; then
+    if [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]]; then
+      echo
+      echo -e  "Total removed: ${removed_count}"
+    fi
+    if [[ -n "${DEBUG}" ]]; then
+      echo "" >> "${LOG_FILE_PATH}"
+      echo -e  "Total removed: ${removed_count}" >> "${LOG_FILE_PATH}"
+    fi
+  else
+    if [[ -z "${IS_SILENT}" ]] && [[ ${force_silent} -ne 1 ]]; then
+      echo -e "${RED}\n${SCRIPTPATH}: Clearing log files failed${NC}"
+    fi
+    if [[ -n "${DEBUG}" ]]; then
+      echo -e "\n${SCRIPTPATH}: Clearing log files failed"
+    fi
+    exit 2
+  fi
 }
 
 
